# Access the id_github file from Secret Manager
steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=atlas-jsonschema-readonly > /root/.ssh/id_github' ]
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=ms-bitbucket-readonly > /root/.ssh/id_bitbucket' ]
    volumes:
    - name: 'ssh'
      path: /root/.ssh
    
# Set up git with key and domain
  - name: gcr.io/cloud-builders/git
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      chmod 600 /root/.ssh/id_github
      chmod 600 /root/.ssh/id_bitbucket
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_github

      Host bitbucket.org
      Hostname bitbucket.org
      IdentityFile /root/.ssh/id_bitbucket
      User git
      EOF
      ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
      ssh-keyscan github.com >> /root/.ssh/known_hosts
      cat /root/.ssh/id_bitbucket
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  - name: 'gcr.io/cloud-builders/git'
    args:
    - ls-remote
    - git@bitbucket.org:makeandship/mongoose-jsonschema-validator.git
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  - name: node:$_NODE_VERSION
    entrypoint: yarn
    args: ['install', '--production=false'] 
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/atlas-275810/mykrobe-atlas-api:$_BUILD_VERSION',
        '-f',
        'deploy/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'atlas-275810/mykrobe-atlas-api:$_BUILD_VERSION']
substitutions:
  _API_URL: https://uat.makeandship.com/wp-json/ms/api
  _TARGET_ENVIRONMENT: prod
  _SERVER_NAME: uat.makeandship.com
  _NODE_VERSION: 12.13.0
  _BUILD_VERSION: v0.0.1