FROM mthomsit/atlas-api:$GO_DEPENDENCY_LABEL_UPSTREAM

# Install dev dependencies
RUN yarn

# Remove duplicate mocks
RUN rm /app/dist/server/modules/__mocks__/*.js

# Copy mongo
RUN mkdir -p /app/tmp/mongo

CMD yarn test:integration