FROM makeandship/atlas-api:$GO_PIPELINE_LABEL

# Install dev dependencies
RUN yarn

# Remove duplicate mocks
RUN rm /app/dist/server/modules/__mocks__/*.js

# Copy mongo
RUN mkdir -p /app/tmp/mongo

CMD yarn test:unit