db:
  image: mongo
  container_name: db
  volumes:
    - /home/ubuntu/data/db:/data/db
  restart: always
  command: --smallfiles --auth
atlas-api:
  build: ..
  dockerfile: ./deploy/Dockerfile
  container_name: atlas-api
  volumes:
    - /home/ubuntu/data/apidoc:/app/doc
    - /home/ubuntu/data/uploads:/app/uploads
  restart: always
  ports:
    - 3001:3000
  environment:
    - NODE_ENV=production
    - MONGO_USER=admin
    - MONGO_PASSWORD=5HKCO4SDkTfy
    - AWS_ACCESS_KEY={{AWS_ACCESS_KEY}}
    - AWS_SECRET_KEY={{AWS_SECRET_KEY}}
    - AWS_REGION={{AWS_REGION}}
    - ATLAS_APP={{ATLAS_APP}}
    - ES_CLUSTER_URL={{ES_CLUSTER_URL}}
  links:
    - db